#ifndef __DAEMONS_H__
#define __DAEMONS_H__

#include <dirs.h>
#include <modules_daemon.h>

#define ACCOUNT_D       DIR_DAEMONS "account"
#define ACTION_D        DIR_DAEMONS "action"
#define ADVANCE_D       DIR_DAEMONS "advance"
#define ALARM_D         DIR_DAEMONS "alarm"
#define ALIAS_D         DIR_DAEMONS "alias"
#define BANK_D          DIR_DAEMONS "bank"
#define BODY_D          DIR_DAEMONS "body"
#define BOOT_D          DIR_DAEMONS "boot"
#define CACHE_D         DIR_DAEMONS "cache"
#define CHAN_D          DIR_DAEMONS "channel"
#define COLOUR_D        DIR_DAEMONS "colour"
#define CONFIG_D        DIR_DAEMONS "config"
#define COORD_D         DIR_DAEMONS "coord"
#define CRASH_D         DIR_DAEMONS "crash"
#define CRAWLER_D       DIR_DAEMONS "crawler"
#define CURRENCY_D      DIR_DAEMONS "currency"
#define DB_D            DIR_DAEMONS "db"
#define DEATH_D         DIR_DAEMONS "death"
#define GH_ISSUES_D     DIR_DAEMONS "github_issues"
#define GMCP_D          DIR_DAEMONS "gmcp"
#define GRAPEVINE_D     DIR_DAEMONS "grapevine"
#define HELP_D          DIR_DAEMONS "help"
#define HTTPC_D         DIR_DAEMONS "httpc"
#define LINES_D         DIR_DAEMONS "lines"
#define LOOT_D          DIR_DAEMONS "loot"
#define MESS_D          DIR_DAEMONS "message"
#define MOVE_D          DIR_DAEMONS "movement"
#define MSSP_D          DIR_DAEMONS "mssp"
#define MUDDY_D         DIR_DAEMONS "muddy"
#define PERSIST_D       DIR_DAEMONS "persist"
#define RESOURCE_D      DIR_DAEMONS "resource"
#define SHUTDOWN_D      DIR_DAEMONS "shutdown"
#define SIGNAL_D        DIR_DAEMONS "signal"
#define SWAP_D          DIR_DAEMONS "swap"
#define TIME_D          DIR_DAEMONS "time"
#define VIRTUAL_D       DIR_DAEMONS "virtual"
#define WEBSOCKET_D     DIR_DAEMONS "websocket_client"

#endif // __DAEMONS_H__
