#ifndef __DIRS_H__
#define __DIRS_H__

#define DIR_ADM                 "/adm/"
#define DIR_ADM_ETC             DIR_ADM "etc/"
#define DIR_ADM_OBJ             DIR_ADM "obj/"
#define DIR_CMDS                "/cmds/"
#define DIR_CMDS_ACTION         DIR_CMDS "action/"
#define DIR_CMDS_ADM            DIR_CMDS "adm/"
#define DIR_CMDS_FILE           DIR_CMDS "files/"
#define DIR_CMDS_OBJECT         DIR_CMDS "object/"
#define DIR_CMDS_STD            DIR_CMDS "std/"
#define DIR_CMDS_DEV            DIR_CMDS "dev/"
#define DIR_DAEMON_MODULES      DIR_DAEMONS "modules/"
#define DIR_DAEMONS             DIR_ADM "daemons/"
#define DIR_DOMAIN              "/d/"
#define DIR_ETC                 "/etc/"
#define DIR_ETC_RESOURCE        DIR_ETC "resource/"
#define DIR_LIB                 "/lib/"
#define DIR_LOG                 "/log/"
#define DIR_OBJ                 "/obj/"
#define DIR_OBJ_MUDLIB          DIR_OBJ "mudlib/"
#define DIR_OBJ_NODE            DIR_OBJ "node/"
#define DIR_STD                 "/std/"
#define DIR_STD_AREA            DIR_STD "area/"
#define DIR_STD_CLASSES         DIR_STD "classes/"
#define DIR_STD_CMD             DIR_STD "cmd/"
#define DIR_STD_EXT             DIR_STD "ext/"
#define DIR_STD_HANDLERS        DIR_STD "handlers/"
#define DIR_STD_HANDLERS_GMCP   DIR_STD_HANDLERS "gmcp/"
#define DIR_STD_LIVING          DIR_STD "living/"
#define DIR_STD_MODULES         DIR_STD "modules/"
#define DIR_STD_OBJECT          DIR_STD "object/"
#define DIR_STD_ROOM            DIR_STD "room/"
#define DIR_STD_TEST            DIR_STD "test/"

#endif // __DIRS_H__
